# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photo', verbose_name='Фото')),
                ('steps', models.BigIntegerField(blank=True, null=True, verbose_name='Общее количество шагов')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='StepUserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('steps', models.BigIntegerField(verbose_name='Количество шагов')),
                ('step_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StepUser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'история пользователя',
                'verbose_name_plural': 'истории пользователей',
            },
        ),
    ]
